#!/bin/bash
COFF=$(tput sgr0)
CBRED=$(tput setab 1)
CBBLACK=$(tput setab 0)
CBLACK=$(tput setaf 0)
CGREEN=$(tput setaf 2)
CRED=$(tput setaf 1)
CBLUE=$(tput setaf 6)
CWHITE=$(tput setaf 7)

if [[ -e /dev/sdb ]]; then
  echo "*********************************
***           ERROR           ***
*********************************
Your drives are not set to RAID 1 mode.
Power down your CloudShell 2, adjust the dip switch,
then hold the RAID Setup key for 30 seconds while powering up."
  exit 0
fi

if [[ -e /dev/sda ]]; then
  if [[ -e /dev/sda1 ]]; then
    echo -e "$CBRED"
    figlet WARNING
    echo -e "$COFF"
    echo -e "${CWHITE}Your disk array already contains partitions / data.${COFF}

Proceeding will wipe all data, including your Nextcloud database if it exists.

This will be like resetting everything to factory settings, losing all data
with no way to recover it if you change your mind.
"

    read -r -p "Do you want to destroy all data and re-initialize? [y/N] " proceed
    echo ""
    if [[ $proceed =~ ^([yY][eE][sS]|[yY])$ ]]; then
      read -r -p "I'm not kidding. You'll lose EVERYTHING! You're sure? [y/N] " proceed
      echo ""
      if [[ $proceed =~ ^([yY][eE][sS]|[yY])$ ]]; then
        echo "You're the boss. Proceeding..."
        echo
        # Instantly destory all partitions on /dev/sda
        dd if=/dev/zero of=/dev/sda bs=512 count=1 > /dev/null 2>&1
      else
        echo "Phew! Aborted."
        exit 1
      fi
    else
      echo "Aborted."
      exit 1
    fi

  fi
else
  echo "You do not have a RAID 1 configured. Please fix and try again."
  exit 0
fi

tmpdir=`mktemp -d -p /usr/local/share/`

# Clear old entries in /etc/fstab
/bin/sed -i~ '/\/mnt\/data/d' /etc/fstab

# Unmount it if mounted
if mount | grep -q "/mnt/data"; then
  umount /mnt/data
fi

# Create /dev/sda1 partition using entire size of array
echo 'type=83' | sfdisk /dev/sda > /dev/null 2>&1

# Create filesystem on /dev/sda1
yes | mkfs.ext3 /dev/sda1

# Get the UUID of /dev/sda1
uuid=$(blkid -s UUID -o value /dev/sda1)

# Create the mountpoint
if [[ ! -e /mnt/data ]]; then
  mkdir /mnt/data
else
  if mount | grep -q "/mnt/data"; then
    umount /mnt/data
  fi
fi

# Make /mnt/data immutable
chattr +i /mnt/data

# Create fstab entry
echo "UUID=$uuid	/mnt/data	ext3	errors=remount-ro,noatime,discard	0	1" >> /etc/fstab

# Set spindown delay and make persistent
echo "## Configuration created by Nebulinux drive-prep command.
## If you modify settings here and then run drive-prep, you will lose your settings.

quiet

/dev/sda {
  ## 0 disable spindown
  ## 1 to 240 = 5 second increments
  ## 241 to 251 30 minutes increments
  #  Nebulinux default is 242 / 1 hour
  spindown_time = 242
}
" > /etc/hdparm.conf

# Mount it
mount -a

if mount | grep -q "/mnt/data"; then

  # Initialize a new database
  systemctl stop mysql
  if [[ -e /var/lib/mysql~ ]]; then
    rm -rf /var/lib/mysql~
  fi
  mv /var/lib/mysql/ /var/lib/mysql~
  mysql_install_db
  systemctl start mysql
  sleep 2
  if [[ ! -e /var/run/mysqld/mysqld.sock ]]; then
    systemctl restart mysql
    sleep 2
    if [[ ! -e /var/run/mysqld/mysqld.sock ]]; then
      echo "I couldn't start MySQL. Please try again."
      exit 1
    fi
  fi

  # Allow install, even if someone already installed previously. After all, user acknowledged that they're destroying EVERYTHING.
  echo "" > /var/www/html/config/CAN_INSTALL

  # Create Nextcloud database and set unique password
  password=$(date +%s | sha256sum | base64 | head -c 32 ; echo)
  echo "CREATE DATABASE nextclouddb;" > $tmpdir/db-create.sql
  echo "GRANT ALL ON nextclouddb.* TO 'nextcloud'@'localhost' IDENTIFIED BY '$password';" >> $tmpdir/db-create.sql
  echo "FLUSH PRIVILEGES;" >> $tmpdir/db-create.sql
  cat $tmpdir/db-create.sql | mysql -u root

  # Lock out the root DB user now that we've initialized everything
  rand=$(date +%s | sha256sum | base64 | head -c 32 ; echo)
  '/usr/bin/mysqladmin' -u root password '$rand'
  '/usr/bin/mysqladmin' -u root -h nebulinux password '$rand'

  # Activate Nextcloud as basedir
  if [[ -d /var/www/html ]]; then
    if [[ -e /var/www/html~ ]]; then
      rm -rf /var/www/html~
    fi
    mv /var/www/html /var/www/html~
    ln -s nextcloud /var/www/html
    chown www-data:www-data /var/www/html
  fi
  chown -R www-data:www-data /mnt/data
  echo "Success! /mnt/data is now setup for your Array. Use this when activating NextCloud."
  echo
  echo "==============================================="
  echo
  echo "All done! You must activate your installation."
  echo
  echo "Visit your server IP in your browser and use the following info:"
  echo
  echo "Username / Password: Create your own"
  echo "Data folder: /mnt/data"
  echo "Database User: nextcloud"
  echo "Database Password: $password"
  echo "Database Name: nextclouddb"
  echo "Database Server: localhost"
  echo
  echo "==============================================="
  echo
  echo "<?php
$""AUTOCONFIG = array (
  'datadirectory' => '/mnt/data',
  'dbtype' => 'mysql',
  'dbname' => 'nextclouddb',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'nebu_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'nextcloud',
  'dbpassword' => '${password}',
);" > /var/www/nextcloud/config/autoconfig.php


else
  # Delete the failed entry from /etc/fstab
  /bin/sed -i~ '/\/mnt\/data/d' /etc/fstab
  echo "Failure!"
fi

# Clean up
rm -rf $tmpdir
